harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
gitFileConfig:
  branch: master
  connectorName: GitHub Account
  repoName: pedrokuhn/helm-chart
  useBranch: true
  useInlineServiceDefinition: false
storeType: HelmSourceRepo
