apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        team: casino
        app: {{.Values.name}}
        workflow: {{.Values.workflow}}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-default.properties: {{.Values.vaultPath}}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/auth-config-project: {{.Values.vaultProject}}
        vault.hashicorp.com/auth-config-role: {{.Values.vaultRole}}
        vault.hashicorp.com/auth-config-service_account: {{.Values.serviceacct}}
        vault.hashicorp.com/auth-config-type: iam
        vault.hashicorp.com/auth-path: auth/gcp_iam
        vault.hashicorp.com/auth-type: gcp
        vault.hashicorp.com/namespace: sag
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: newrelic-infra-flex
        image: {{.Values.image}}
        imagePullPolicy: Always
        env:
        - name: NRIA_LICENSE_KEY
          value: ""
        - name: NRIA_VERBOSE
          value: "1"
        - name: CASINO_ENV
          valueFrom:
            configMapKeyRef:
              name: nri-flex-environment-variables
              key: CASINO_ENV
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
          privileged: true
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "250Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /host
          name: host-volume
          readOnly: true
        - mountPath: /run/docker.sock
          name: host-docker-socket
        - mountPath: /etc/newrelic-infra/integrations.d/
          name: nri-integration-cfg-volume
      volumes:
      - name: host-volume
        hostPath:
        path: /
      - name: host-docker-socket
        hostPath:
        path: /var/run/docker.sock
      - name: nri-default-integration-cfg-volume
        configMap:
        name: nri-default-integration-cfg
      - name: nri-integration-cfg-volume
        configMap:
        name: nri-integration-cfg

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-integration-cfg
data:
  nri-flex.yml: |-
    integrations:
    - name: nri-flex
      config:
      name: Casino Flex checks
    apis:
    - database: mysql
      name: pigbeeMysqlChecks
      event_type: CasinoMysqlCheck
      db_conn: {{.Values.pigbeeFeaturesConnectionString}}
      db_queries:
    - name: MEMCACHE_ITEM_PERFORMANCE
      run: "select `key`, avg_time from server_performance_logs where type = 'get' and `key` like 'Perf.memcache0%' and DATE_SUB(NOW(),INTERVAL 10 MINUTE) <= updated_on ORDER BY updated_on DESC"
      custom_attributes:
      env: {{.Values.casinoEnv}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-flex-environment-variables
data:
  CASINO_ENV: "casino-game-features"