harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: Pedro Staging
failureStrategies:
- actionAfterTimeout: END_EXECUTION
  executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  manualInterventionTimeout: 1209600000
  repairActionCode: MANUAL_INTERVENTION
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: KUBERNETES
  computeProviderName: GKE cluster
  daemonSet: false
  infraDefinitionName: staging-namespace
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Export Manifest Deployment
      properties:
        exportManifests: true
        inheritManifests: false
        stateTimeoutInMinutes: 10
    - type: SHELL_SCRIPT
      name: Diff Manifests
      properties:
        commandPath: null
        connectionAttributeName: null
        executeOnDelegate: true
        host: null
        includeInfraSelectors: true
        outputVars: ''
        publishAsVar: false
        scriptString: |-
          cat <<EOF
          file secret:
          ${k8sResources.manifests}
          EOF
        scriptType: BASH
        sshKeyRefName: null
        sweepingOutputName: null
        sweepingOutputScope: null
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 60000
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: New Created Service
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: GKE cluster
  daemonSet: false
  infraDefinitionName: staging-namespace
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: New Created Service
  statefulSet: false
templatized: false
