# harness.io/skip-file-for-deploy 

apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
data:
  config.properties: -|
{{ .Values.env.config.config_properties | b64dec | indent 4}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---