# harness.io/skip-file-for-deploy 

apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
data:
{{.Values.env.config | toYaml | indent 2}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---