# harness.io/skip-file-for-deploy 
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  config.properties: "tst"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---