# harness.io/skip-file-for-deploy

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
    harness.io/managed: true
  name: {{.Values.name}}-destinationrule
spec:
  host: {{.Values.name}}.{{.Values.namespace}}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: RANDOM