apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  config.sh: |
    echo "test file"
---

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: busybox:latest
        args:
        - sleep
        - "1000000"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.sh
      volumes:
        - name: config-volume
          configMap:
            name: {{.Values.name}}